### ISSUE TITLE
Buildpack making our app unavailable

### ISSUE THREAD

**Issue by atmos** [heroku/heroku-buildpack-metrics#20] opened 2017-07-26 20:32 UTC
We had a weird bug this week where our application was down and we couldn't figure out why.

Using `run:inside` to get a console we saw a ton of agentmon failures. Once I figured out that it might be coming from the metrics buildpack I went ahead and removed it. The app was available and working after another release.

/cc @heroku/tools @daneharrigan

**Comment by freeformz** [comment] 2017-07-26 22:11
Interesting. I'm not sure why the buildpack would do that. What app is it?

**Comment by daneharrigan** [comment] 2017-08-08 22:03
The app is heroku-zipkin-production

**Comment by apg** [comment] 2017-08-08 22:18
There are two potential problems: the JAR that gets setup, and the agent that reads prometheus values from the running application. We've not yet seen any reports of problems with the agent, though one might expect that since we're doing `while true {run-agent}` to deal with crashes, instead of using a process monitor, it *could* spawn lots and lots of processes or something similar, on an error.

Perhaps more likely, however, is that zipkin starts the JVM with an -javaagent and our premain somehow interacts poorly with it? 

Keep in mind, I have nothing to support either claim, but intuitively, these are the things I feel could be issues.

**Comment by jkutner** [comment] 2017-09-28 15:05
I feel like I chatted with someone in Slack about this, and identified the problem. But the details evade my memory. @atmos any recollection of that conversation?

**Comment by ys** [comment] 2017-09-28 18:00
I had issues with it! Was running some other java bin before zipkin and
that one was stuck in a loop instead of exiting

**Comment by jkutner** [comment] 2017-09-28 18:03
@ys i think it was caused by the JMX options in `JAVA_TOOL_OPTIONS`. sound familiar? I've seen that happen with tools I run via `heroku run`. Maybe we need a documented way to selectively disable the opts.

**Comment by ys** [comment] 2017-09-28 18:05
Yes had to unset it and do `JAVA_TOOL_OPTIONS="" java ...`

**Comment by freeformz** [comment] 2017-10-08 15:43
@jkutner Is there anything I can do to help move resolution forward?

**Comment by jkutner** [comment] 2017-10-08 15:58
@freeformz no. it's on me.

**Comment by jkutner** [comment] 2017-10-26 20:57
I'm probably going to punt on this until we move this logic into the `heroku/jvm` buildpack.

**Comment by ys** [comment] 2017-10-30 10:22
We got it again with a ruby app and the `heroku ps:exec`, we get in a loop with Agentmon

**Comment by micke** [comment] 2018-05-07 08:33
This just happened to one of our applications too

**Comment by jkutner** [comment] 2018-05-07 13:44
@lisinge what language are you using the buildpack with? The buildpack is [no longer needed to use the feature](https://devcenter.heroku.com/articles/language-runtime-metrics-jvm#getting-started) (it was only needed during the Beta). You should be able to remove the buildpack, and continue to get metrics in your dashboard.

**Comment by micke** [comment] 2018-05-08 09:59
@jkutner alright. yeah i just removed the buildpack and now it works fine.
We used it with scala/play

**Comment by jkutner** [comment] 2018-05-08 13:41
@lisinge sorry for the trouble

**Comment by freeformz** [comment] 2018-05-16 17:13
Java apps don't use this buildpack anymore so I'm going to close this.

**Closed as completed by freeformz** 2018-05-16 17:13 UTC
